export default function LegalPage() {
    return (
        <div className="min-h-screen py-20 px-6 sm:px-12 lg:px-16">
            <div className="mx-auto max-w-4xl space-y-12">

                <div className="text-center space-y-4">
                    <h1 className="font-display text-4xl font-bold text-white">Legal & Credits</h1>
                    <p className="text-lg text-white/60">Transparency about the technology powering Chesstory.</p>
                </div>

                <div className="glass-card rounded-2xl p-8 space-y-8">

                    <section className="space-y-4">
                        <h2 className="text-2xl font-bold text-white">Open Source Acknowledgments</h2>
                        <p className="text-white/70 leading-relaxed">
                            Chesstory is built upon the shoulders of giants. We gratefully acknowledge the following open source projects that make our analysis possible.
                        </p>

                        <div className="grid gap-6 md:grid-cols-2">
                            <div className="rounded-xl bg-white/5 p-6 border border-white/10">
                                <h3 className="text-lg font-bold text-accent-teal mb-2">Stockfish</h3>
                                <p className="text-sm text-white/60 mb-4">
                                    The world&apos;s strongest chess engine. Used for evaluation and analysis generation.
                                </p>
                                <div className="text-xs text-white/40 space-y-1">
                                    <p>License: GPL-3.0</p>
                                    <a href="https://stockfishchess.org" className="underline hover:text-white/60" target="_blank">Official Website</a>
                                </div>
                            </div>

                            <div className="rounded-xl bg-white/5 p-6 border border-white/10">
                                <h3 className="text-lg font-bold text-accent-teal mb-2">Lichess (Chessground)</h3>
                                <p className="text-sm text-white/60 mb-4">
                                    The beautiful interactive board UI used throughout our application.
                                </p>
                                <div className="text-xs text-white/40 space-y-1">
                                    <p>License: GPL-3.0 / MIT</p>
                                    <a href="https://github.com/lichess-org/chessground" className="underline hover:text-white/60" target="_blank">GitHub Repository</a>
                                </div>
                            </div>
                            <div className="rounded-xl bg-white/5 p-6 border border-white/10">
                                <h3 className="text-lg font-bold text-accent-teal mb-2">Scalachess</h3>
                                <p className="text-sm text-white/60 mb-4">
                                    Scala library for chess rules and notation, maintained by Lichess.
                                </p>
                                <div className="text-xs text-white/40 space-y-1">
                                    <p>License: MIT</p>
                                    <a href="https://github.com/lichess-org/scalachess" className="underline hover:text-white/60" target="_blank">GitHub Repository</a>
                                </div>
                            </div>
                        </div>
                    </section>

                    <div className="h-px bg-white/10" />

                    <section className="space-y-4">
                        <h2 className="text-xl font-bold text-white">Disclaimer</h2>
                        <div className="prose prose-invert prose-sm text-white/70">
                            <p>
                                Chesstory is an independent service and is not affiliated with, endorsed by, or sponsored by Lichess.org or the Stockfish developers.
                            </p>
                            <p>
                                All analysis provided by Chesstory, including &quot;Practicality Scores&quot; and &quot;Study Scores&quot;, are estimates generated by our proprietary algorithms and AI models. They should be used for educational purposes and not as definitive truth.
                            </p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
}
