steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gen-lang-client-0162856170/web:latest', '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}', '--build-arg', 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}', '--build-arg', 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}', '-f', 'Dockerfile.frontend', '.']
images:
  - 'gcr.io/gen-lang-client-0162856170/web:latest'
timeout: 1200s
substitutions:
  _NEXT_PUBLIC_API_URL: "https://chesstory-api-145435701096.us-central1.run.app"
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: "145435701096-k889gqvpa4gvac76i87kolp9cq2em8e7.apps.googleusercontent.com"
  _NEXT_PUBLIC_API_KEY: "3f8a92b1c4d5e6f7a0b1c2d3e4f5a6b7c8d9e0f1"
