steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gen-lang-client-0162856170/web:latest', '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}', '--build-arg', 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}', '-f', 'Dockerfile.frontend', '.']
images:
  - 'gcr.io/gen-lang-client-0162856170/web:latest'
timeout: 1200s
substitutions:
  _NEXT_PUBLIC_API_URL: "https://chesstory-api-145435701096.us-central1.run.app" # Default value, override in command
  _NEXT_PUBLIC_GOOGLE_CLIENT_ID: "145435701096-k889gqvpa4gvac76i87kolp9cq2em8e7.apps.googleusercontent.com"
