package lila.accountintel.opening

import chess.Color

object EcoPerspectiveTable:

  case class Entry(family: String, chooserSide: Option[Color])

  private val allCodes: List[String] =
    ('A' to 'E').toList.flatMap(letter => (0 to 99).toList.map(num => f"$letter$num%02d"))

  val entries: Map[String, Entry] =
    val builder = Map.newBuilder[String, Entry]

    def put(code: String, family: String, chooserSide: Option[Color]) =
      builder += code -> Entry(family, chooserSide)

    def putRange(start: String, end: String, family: String, chooserSide: Option[Color]) =
      val prefix = start.head
      val from = start.drop(1).toInt
      val to = end.drop(1).toInt
      (from to to).foreach(num => put(f"$prefix$num%02d", family, chooserSide))

    put("A00", "Amar Opening", Some(Color.White))
    put("A01", "Nimzo-Larsen Attack", Some(Color.White))
    putRange("A02", "A03", "Bird Opening", Some(Color.White))
    putRange("A04", "A06", "Zukertort Opening", Some(Color.White))
    putRange("A07", "A08", "King's Indian Attack", Some(Color.White))
    put("A09", "Réti Opening", Some(Color.White))
    putRange("A10", "A11", "English Opening", Some(Color.White))
    put("A12", "Réti Opening", Some(Color.White))
    putRange("A13", "A17", "English Opening", Some(Color.White))
    putRange("A18", "A19", "English Opening: Mikenas-Carls Variation", Some(Color.White))
    putRange("A20", "A29", "English Opening: King's English Variation", Some(Color.White))
    putRange("A30", "A39", "English Opening: Symmetrical Variation", Some(Color.White))
    put("A40", "Englund Gambit", Some(Color.Black))
    put("A41", "Queen's Pawn Game", Some(Color.White))
    put("A42", "Modern Defense", Some(Color.Black))
    putRange("A43", "A44", "Benoni Defense: Old Benoni", Some(Color.Black))
    put("A45", "Indian Defense", Some(Color.Black))
    put("A46", "Döry Defense", Some(Color.Black))
    put("A47", "Pseudo Queen's Indian Defense", Some(Color.Black))
    put("A48", "East Indian Defense", Some(Color.Black))
    put("A49", "Indian Defense", Some(Color.Black))
    put("A50", "Slav Indian", Some(Color.Black))
    putRange("A51", "A52", "Budapest Defense", Some(Color.Black))
    putRange("A53", "A55", "Old Indian Defense", Some(Color.Black))
    put("A56", "Benoni Defense", Some(Color.Black))
    put("A57", "Benko Gambit", Some(Color.Black))
    putRange("A58", "A59", "Benko Gambit Accepted", Some(Color.Black))
    putRange("A60", "A79", "Benoni Defense", Some(Color.Black))
    putRange("A80", "A99", "Dutch Defense", Some(Color.Black))

    put("B00", "Borg Defense", Some(Color.Black))
    put("B01", "Scandinavian Defense", Some(Color.Black))
    putRange("B02", "B05", "Alekhine Defense", Some(Color.Black))
    put("B06", "Modern Defense", Some(Color.Black))
    put("B07", "Maróczy Defense", Some(Color.Black))
    putRange("B08", "B09", "Pirc Defense", Some(Color.Black))
    putRange("B10", "B19", "Caro-Kann Defense", Some(Color.Black))
    putRange("B20", "B21", "Sicilian Defense", Some(Color.Black))
    put("B22", "Sicilian Defense: Alapin Variation", Some(Color.White))
    putRange("B23", "B26", "Closed Sicilian", Some(Color.White))
    putRange("B27", "B29", "Sicilian Defense", Some(Color.Black))
    put("B30", "Sicilian Defense: Old Sicilian", Some(Color.Black))
    put("B31", "Rossolimo Attack", Some(Color.White))
    putRange("B32", "B39", "Sicilian Defense: Accelerated Dragon", Some(Color.Black))
    put("B40", "Sicilian Defense", Some(Color.Black))
    putRange("B41", "B43", "Sicilian Defense: Kan Variation", Some(Color.Black))
    putRange("B44", "B49", "Sicilian Defense: Taimanov Variation", Some(Color.Black))
    put("B50", "Sicilian Defense", Some(Color.Black))
    putRange("B51", "B52", "Moscow Variation", Some(Color.White))
    put("B53", "Chekhover Variation", Some(Color.White))
    put("B54", "Sicilian Defense", Some(Color.Black))
    put("B55", "Prins Variation", Some(Color.White))
    putRange("B56", "B59", "Sicilian Defense: Classical Variation", Some(Color.Black))
    putRange("B60", "B69", "Richter-Rauzer Variation", Some(Color.White))
    putRange("B70", "B79", "Sicilian Defense: Dragon Variation", Some(Color.Black))
    putRange("B80", "B85", "Sicilian Defense: Scheveningen Variation", Some(Color.Black))
    putRange("B86", "B89", "Sozin Attack", Some(Color.White))
    putRange("B90", "B99", "Sicilian Defense: Najdorf Variation", Some(Color.Black))

    putRange("C00", "C02", "French Defense", Some(Color.Black))
    putRange("C03", "C09", "French Defense: Tarrasch Variation", Some(Color.White))
    put("C10", "French Defense: Marshall Gambit", Some(Color.White))
    put("C11", "French Defense: Classical Variation", Some(Color.Black))
    put("C12", "French Defense: McCutcheon Variation", Some(Color.Black))
    putRange("C13", "C14", "French Defense: Classical Variation", Some(Color.Black))
    putRange("C15", "C19", "French Defense: Winawer Variation", Some(Color.Black))
    put("C20", "King's Pawn Game", Some(Color.White))
    putRange("C21", "C22", "Center Game", Some(Color.White))
    putRange("C23", "C24", "Bishop's Opening", Some(Color.White))
    putRange("C25", "C29", "Vienna Game", Some(Color.White))
    put("C30", "King's Gambit", Some(Color.White))
    putRange("C31", "C32", "Falkbeer Countergambit", Some(Color.Black))
    putRange("C33", "C39", "King's Gambit Accepted", Some(Color.Black))
    put("C40", "Latvian Gambit", Some(Color.Black))
    put("C41", "Philidor Defense", Some(Color.Black))
    putRange("C42", "C43", "Petrov's Defense", Some(Color.Black))
    put("C44", "King's Knight Opening", Some(Color.White))
    put("C45", "Scotch Game", Some(Color.White))
    put("C46", "Three Knights Opening", Some(Color.White))
    putRange("C47", "C49", "Four Knights Game", Some(Color.White))
    putRange("C50", "C54", "Italian Game", Some(Color.White))
    putRange("C55", "C59", "Italian Game: Two Knights Defense", Some(Color.Black))
    put("C60", "Ruy Lopez", Some(Color.White))
    put("C61", "Ruy Lopez: Bird Variation", Some(Color.Black))
    put("C62", "Ruy Lopez: Steinitz Defense", Some(Color.Black))
    put("C63", "Ruy Lopez: Schliemann Defense", Some(Color.Black))
    put("C64", "Ruy Lopez: Classical Variation", Some(Color.Black))
    putRange("C65", "C67", "Ruy Lopez: Berlin Defense", Some(Color.Black))
    putRange("C68", "C69", "Ruy Lopez: Exchange Variation", Some(Color.White))
    putRange("C70", "C79", "Ruy Lopez: Morphy Defense", Some(Color.Black))
    putRange("C80", "C83", "Ruy Lopez: Open Variation", Some(Color.Black))
    putRange("C84", "C99", "Ruy Lopez: Closed Variation", Some(Color.Black))

    put("D00", "Queen's Pawn Game", Some(Color.White))
    put("D01", "Rapport-Jobava System", Some(Color.White))
    put("D02", "Queen's Pawn Game", Some(Color.White))
    put("D03", "Torre Attack", Some(Color.White))
    putRange("D04", "D05", "Colle System", Some(Color.White))
    put("D06", "Queen's Gambit", Some(Color.White))
    put("D07", "Queen's Gambit Declined: Chigorin Defense", Some(Color.Black))
    putRange("D08", "D09", "Albin Countergambit", Some(Color.Black))
    putRange("D10", "D19", "Slav Defense", Some(Color.Black))
    putRange("D20", "D29", "Queen's Gambit Accepted", Some(Color.Black))
    putRange("D30", "D31", "Queen's Gambit Declined", Some(Color.Black))
    putRange("D32", "D34", "Tarrasch Defense", Some(Color.Black))
    putRange("D35", "D39", "Queen's Gambit Declined", Some(Color.Black))
    putRange("D40", "D42", "Semi-Tarrasch Defense", Some(Color.Black))
    putRange("D43", "D49", "Semi-Slav Defense", Some(Color.Black))
    putRange("D50", "D69", "Queen's Gambit Declined", Some(Color.Black))
    putRange("D70", "D79", "Neo-Grünfeld Defense", Some(Color.Black))
    putRange("D80", "D99", "Grünfeld Defense", Some(Color.Black))

    putRange("E00", "E09", "Catalan Opening", Some(Color.White))
    put("E10", "Indian Defense", Some(Color.Black))
    put("E11", "Bogo-Indian Defense", Some(Color.Black))
    putRange("E12", "E19", "Queen's Indian Defense", Some(Color.Black))
    putRange("E20", "E59", "Nimzo-Indian Defense", Some(Color.Black))
    putRange("E60", "E99", "King's Indian Defense", Some(Color.Black))

    val result = builder.result()
    val missing = allCodes.toSet -- result.keySet
    require(missing.isEmpty, s"Missing ECO perspective entries: ${missing.toList.sorted.mkString(", ")}")
    result

