include "base"
include "version"

user.password.bpass.secret = "9qEYN0ThHer1KWLNekA76Q=="

net.site.name = "Chesstory"
net.domain = ${?LILA_DOMAIN}
net.socket.domains = [ ${?LILA_DOMAIN} ]
net.asset.base_url = ${?LILA_URL}
net.base_url = ${?LILA_URL}
net.email = ${?PUBLIC_CONTACT_EMAIL}
net.ratelimit = ${?ENABLE_RATE_LIMITING}

security.password_reset.secret = ${?PASSWORD_RESET_SECRET}
security.email_confirm.secret = ${?EMAIL_CONFIRM_SECRET}
security.email_change.secret = ${?EMAIL_CHANGE_SECRET}
security.login_token.secret = ${?LOGIN_TOKEN_SECRET}

mongodb.uri = "mongodb://mongodb?appName=lila"
redis.uri = "redis://redis"

game.gifUrl = "http://lila_gif:6175"

search.enabled = true
search.endpoint = "http://lila_search_app:9673"

memo.picfit.endpointGet = ${?LILA_URL}
memo.picfit.endpointPost = "http://picfit:3001"

mailer.primary.mock = ${?MOCK_EMAIL}
mailer.primary.tls = ${?SMTP_TLS}
mailer.primary.host = ${?SMTP_HOST}
mailer.primary.port = ${?SMTP_PORT}
mailer.primary.user = ${?SMTP_USER}
mailer.primary.password = ${?SMTP_PASSWORD}
mailer.primary.sender = ${?SMTP_SENDER}
mailer.secondary = ${mailer.primary}
security.email_confirm.enabled = true

push.web.url = "http://lila_push:9054"
push.web.vapid_public_key = "BDTVzVZ3_f83JgH1SJmZrhg-FNZ36Sixc_zrR1-1ZGVHUPmFeU6Q_-JQLN8NF5niYW_1jRU47aPczYA0FbgUCus="

swiss.bbpairing = "/opt/bbpPairings/bbpPairings.exe"

kamon.enabled = ${?ENABLE_MONITORING}
kamon.influxdb.hostname = "influxdb"
kamon.influxdb.authentication.token = "secret"
kamon.metric.tick-interval = 2 seconds
kamon.prometheus.lilaKey = "x"
api.influx_event.endpoint = ""
api.influx_event.env = ""

plan.stripe.keys.public = "pk_test_123"
plan.stripe.keys.secret = "sk_test_123"
plan.payPal.keys.public = "sb"

support.links.patreon = ${?SUPPORT_PATREON_URL}
support.links.githubSponsors = ${?SUPPORT_GITHUB_SPONSORS_URL}
support.links.buyMeACoffee = ${?SUPPORT_BMC_URL}

streamer.twitch.endpoint = "http://caddy/static/twitch-streamers.json"
streamer.twitch.client_id = "twitch-client-id"
streamer.twitch.secret = "twitch-secret"

hcaptcha.enabled = ${?HCAPTCHA_ENABLED}
hcaptcha.public.sitekey = ${?HCAPTCHA_SITEKEY}
hcaptcha.secret = ${?HCAPTCHA_SECRET}

explorer.endpoint = ${?EXPLORER_API_BASE}
explorer.internal_endpoint = ${?EXPLORER_API_BASE}
explorer.tablebase_endpoint = ${?TABLEBASE_API_BASE}

external.import.lichess.api_base = ${?LICHESS_IMPORT_API_BASE}
external.import.lichess.web_base = ${?LICHESS_WEB_BASE}
external.import.chesscom.api_base = ${?CHESSCOM_API_BASE}
