services:
  mongodb:
    image: mongo:7.0.24-jammy
    restart: unless-stopped
    command: mongod --bind_ip_all --replSet rs0
    healthcheck:
      test: mongosh --quiet /scripts/replica-set.js
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    ports:
      - "27017:27017"
    volumes:
      - ./repos/lila:/lila
      - ./scripts:/scripts
    profiles:
      - base

  mongodb_secondary:
    image: mongo:7.0.24-jammy
    restart: unless-stopped
    command: mongod --bind_ip_all --replSet rs0
    profiles:
      - base

  redis:
    image: redis:8.0.3-alpine3.21
    restart: unless-stopped
    ports:
      - "6379:6379"
    profiles:
      - base
