import { type VNode, type VNodeData, type VNodeChildElement, type Hooks, type Attrs, type Classes } from 'snabbdom';
import { icons } from '../icons';
export type { Attrs, Hooks, Classes, VNode, VNodeData, VNodeChildElement };
export type MaybeVNode = VNode | string | null | undefined;
export type MaybeVNodes = MaybeVNode[];
export declare function onInsert<A extends HTMLElement>(f: (element: A) => void): Hooks;
export declare function bind<K extends keyof GlobalEventHandlersEventMap>(eventName: K, f: (ev: GlobalEventHandlersEventMap[K]) => any, redraw?: Redraw, passive?: boolean): Hooks;
export declare const dataIcon: (icon: string) => Attrs;
export declare function icon(name: keyof typeof icons, className?: string): VNode;
export type LooseVNode = VNodeChildElement | boolean;
export type LooseVNodes = LooseVNode | LooseVNodes[];
export declare function hl(sel: string, dataOrKids?: VNodeData | LooseVNodes, kids?: LooseVNodes): VNode;
